UPDATE Player SET first_name = 'Mitul', last_name = 'Marma', date_of_birth = '2003-12-31', position = 'Goalkeeper', current_club_id = 2, fee = 200000 WHERE player_id = 13;
UPDATE Player SET first_name = 'Sujon', last_name = 'Hossain', date_of_birth = '1996-12-31', position = 'Goalkeeper', current_club_id = 3, fee = 175000 WHERE player_id = 12;
UPDATE Player SET first_name = 'Mehedi', last_name = 'Hasan Srabon', date_of_birth = '2005-12-31', position = 'Goalkeeper', current_club_id = 11, fee = 50000 WHERE player_id = 1;
UPDATE Player SET first_name = 'Tariq', last_name = 'Kazi', date_of_birth = '2000-12-31', position = 'Centre-Back', current_club_id = NULL, fee = 125000 WHERE player_id = 14;
UPDATE Player SET first_name = 'Shakil', last_name = 'Ahad Topu', date_of_birth = '2005-12-31', position = 'Centre-Back', current_club_id = 3, fee = 100000 WHERE player_id = 2;
UPDATE Player SET first_name = 'Saad', last_name = 'Uddin', date_of_birth = '1998-12-31', position = 'Left-Back', current_club_id = 11, fee = 150000 WHERE player_id = 22;
UPDATE Player SET first_name = 'Abdullah', last_name = 'Omar', date_of_birth = '1994-12-31', position = 'Left-Back', current_club_id = 7, fee = 100000 WHERE player_id = 24;
UPDATE Player SET first_name = 'Zayyan', last_name = 'Ahmed', date_of_birth = '2003-12-31', position = 'Left-Back', current_club_id = 10, fee = 50000 WHERE player_id = 19;
UPDATE Player SET first_name = 'Rahmat', last_name = 'Mia', date_of_birth = '1999-12-31', position = 'Right-Back', current_club_id = 3, fee = 175000 WHERE player_id = 3;
UPDATE Player SET first_name = 'Bishwanath', last_name = 'Ghosh', date_of_birth = '1999-12-31', position = 'Right-Back', current_club_id = 11, fee = 50000 WHERE player_id = 12;
UPDATE Player SET first_name = 'Hamza', last_name = 'Choudhury', date_of_birth = '1997-12-31', position = 'Defensive Midfield', current_club_id = 11, fee = 5000000 WHERE player_id = 8;
UPDATE Player SET first_name = 'Mohammad', last_name = 'Ridoy', date_of_birth = '2001-12-31', position = 'Defensive Midfield', current_club_id = 11, fee = 250000 WHERE player_id = 5;
UPDATE Player SET first_name = 'Jamal', last_name = 'Bhuyan', date_of_birth = '1990-12-31', position = 'Defensive Midfield', current_club_id = 12, fee = 75000 WHERE player_id = 6;
UPDATE Player SET first_name = 'Quazem', last_name = 'Shah', date_of_birth = '1998-12-31', position = 'Central Midfield', current_club_id = 2, fee = 200000 WHERE player_id = 21;
UPDATE Player SET first_name = 'Sohel', last_name = 'Rana', date_of_birth = '1994-12-31', position = 'Central Midfield', current_club_id = 11, fee = 175000 WHERE player_id = 17;
UPDATE Player SET first_name = 'Shamit', last_name = 'Shome', date_of_birth = '1997-12-31', position = 'Central Midfield', current_club_id = NULL, fee = 175000 WHERE player_id = 23;
UPDATE Player SET first_name = 'Fahamedul', last_name = 'Islam', date_of_birth = '2006-12-31', position = 'Left Midfield', current_club_id = 9, fee = 10000 WHERE player_id = 25;
UPDATE Player SET first_name = 'Shekh', last_name = 'Morsalin', date_of_birth = '2005-12-31', position = 'Attacking Midfield', current_club_id = 2, fee = 150000 WHERE player_id = 7;
UPDATE Player SET first_name = 'Foysal', last_name = 'Ahmed Fahim', date_of_birth = '2001-12-31', position = 'Left Winger', current_club_id = 11, fee = 200000 WHERE player_id = 11;
UPDATE Player SET first_name = 'Shahriar', last_name = 'Emon', date_of_birth = '2000-12-31', position = 'Right Winger', current_club_id = 11, fee = 150000 WHERE player_id = 9;
UPDATE Player SET first_name = 'Mirajul', last_name = 'Islam', date_of_birth = '2006-12-31', position = 'Second Striker', current_club_id = 2, fee = 75000 WHERE player_id = 10;
UPDATE Player SET first_name = 'Arman', last_name = 'Foysal Akash', date_of_birth = '2003-12-31', position = 'Centre-Forward', current_club_id = 6, fee = 75000 WHERE player_id = 20;
UPDATE Player SET first_name = 'Sumon', last_name = 'Reza', date_of_birth = '1995-12-31', position = 'Centre-Forward', current_club_id = 3, fee = 50000 WHERE player_id = 26;
